### ISSUE TITLE
Warning when pod install when add lib .Can't merge user_target_xcconfig for pod targets. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

### ISSUE THREAD

**Issue by phucph1998** [map4d/map4d-map-react-native#25]
Can't merge user_target_xcconfig for pod targets: ["FaceDetection", "MLKitCore", "MLKitCommon", "MLKitFaceDetection", "MLKitVision", "Map4dMapUtils"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

**Comment by suale-dev** [comment]
Fixed on latest version

**Comment by memolopezmx** [comment]
Fixed on latest version

??

What latest version?
