### ISSUE TITLE
run debug duplicate symbols for architecture x86_64 when installing the latest version 2.6.0 with react-native-maps

### ISSUE THREAD

**Issue by phucph1998** [map4d/map4d-map-react-native#26]
run debug duplicate symbols for architecture x86_64 when installing the latest version 2.6.0 with react-native-maps 

but version 2.4.0 or older parallel use with react-native-maps

<img width="579" alt="Screen Shot 2022-09-26 at 14 56 19" src="https://user-images.githubusercontent.com/54024031/192226055-a2174ff7-0fce-411d-984d-228db5301eaa.png">

**Comment by omyto** [comment]
Fixed on latest Map4dMapUtils version.
Go to ios folder and run command below to update Map4dMapUtils 
```shell
pod repo update
pod update Map4dMapUtils
```
