### ISSUE TITLE
Lỗi cài đặt thư viện

### ISSUE THREAD

**Issue by thiensoai** [map4d/map4d-map-react-native#30]
Tôi tạo 1 dự án mới và cài thư viện. Sau khi cấu hình và chạy dự án thì gặp vấn đề như trong ảnh.
Có bất kỳ giải pháp nào cho trường hợp này không?
Tôi sử dụng phiên bản react-native 0.71.2
<img width="912" alt="Screenshot 2023-05-26 174851" src="https://github.com/map4d/map4d-map-react-native/assets/134698822/33761206-7e9f-4d1b-aba4-f37f9ccacc71">

**Comment by omyto** [comment]
Hi @thiensoai ,

Tôi nghĩ vấn đề có lẽ do kết nối internet không ổn định.
Bạn có thể thử lại được không?

**Comment by thiensoai** [comment]
Tôi thử lại nhiều lần, đã được kết nốt internet rất ổn định và thực hiện đúng như các bước theo hướng dẫn:
https://docs.map4d.vn/map4d-map/react-native/v2.6/#/
Nhưng vẫn bị lỗi như ảnh trên.
theo tôi thấy như trong ảnh lỗi nó: "Could not find any version that matches vn.map4d:Map4dMap "

**Comment by omyto** [comment]
> "Could not find any version that matches vn.map4d:Map4dMap "

Hi @thiensoai, Có vẻ gradle không tìm kiếm thư viện ở map4d maven repo.
Bạn vui lòng kiểm tra lại xem đã thêm đoạn bên dưới vào **build.gradle** hay chưa?

```groovy
allprojects {
    repositories {
        maven {
            url = "https://packages.map4d.vn/repository/maven-public"
        }
    }
}

```

**Comment by map4d** [comment]
Nếu không có vấn đề gì nữa thì mình xin phép close issue tại đây.
Cảm ơn vì đã sử dụng Map4D
